apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-dev
  labels:
    app: capstone-dev
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-dev
  template:
    metadata:
      labels:
        app: capstone-dev
    spec:
      containers:
        - name: capstone-dev
          image: <<docker_image>>:<<tag>>
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-dev
  labels:
    app: capstone-dev
spec:
  type: LoadBalancer
  selector:
    app: capstone-dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
