apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-deployment
    spec:
      containers:
        - name: capstone-deployment
          image: 49shine/capstone:3230e0b
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
