apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-deployment
    spec:
      containers:
        - name: capstone-dev
          image: 49shine/capstone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: ccapstone-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
