apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
  labels:
    app: capstone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstone-loadbalancer
  ports:
    - port: 80
      targetPort: 80
